all:
		make P1
		make P2
		make P3
		make P4

P1:
		rm -f obj/*
		make -f MakefileP1

P2:
		rm -f obj/*
		make -f MakefileP2

P3:
		rm -f obj/*
		make -f MakefileP3

P4:
		rm -f obj/*
		make -f MakefileP4

clean:
		rm -f obj/*
		rm -f bin/*
